# Generated by Django 5.1.3 on 2024-11-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_legajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DOC', 'Docente'), ('ALU', 'Alumno')], default='ALU', max_length=5),
        ),
    ]
